### ISSUE TITLE
Request - 1.12.2 Simply add a way so darkness does not kill when submerged in water!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Shinoow/Hungering-Darkness#5]
I wanted to make mining dangerous - it was going great except even water kills. I love this mod but it deeply needs to disable what it does when players are submerged in water. (Bubble meter pops up.)

**Comment by P3rf3ctXZer0** [comment]
You could add a shine potion - "The light of your soul keeps the darkness at bay" this way it is also lore friendly. Lesser 5mins and greater 15mins variants

**Comment by Shinoow** [comment]
I'm gonna go with being submerged in water stops the darkness damage, since that's how it should've been from the start (forgot to take that into account).
Adding a potion effect would stray from the "design philosophy" of the mod (not adding any additional content besides the specific feature it introduces). Considering the properties that can already be configured along with the mod integrations, adding a potion effect whose only purpose is to also counter it feels like feature bloat at that point.
Also, the mod is pretty much loreless, so having something lore friendly would beg the question "lore friendly towards what".

**Comment by P3rf3ctXZer0** [comment]
I made a story that an ancient evil lurks in the darkness of Minecraftia. lol sorry just a bit rp. The creator of the end reaps all souls foolish enough to embrace the dark.

**Comment by P3rf3ctXZer0** [comment]
Thanks @Shinoow : D
